import { ArrowDown, ArrowRight, CheckCircle2, CircleDot } from "lucide-react";
import { Fact } from "@/components/governance/Fact";
import { Shell } from "@/components/presenter/Shell";

const metrics = [
  ["Sanction TAT", "baseline → pilot", "Days from complete evidence pack to sanction"],
  ["Fully-loaded cost / decision", "₹ baseline → pilot", "Include officer, review, rework and tooling"],
  ["Officer throughput", "decisions / officer", "Count only decisions that pass quality review"],
  ["CAM quality", "blind score", "Bank credit committee scores without knowing the author"],
  ["Conflicts + stale-data catches", "count + rate", "Caught before sanction, with retraction retained"],
  ["Scheme capture rate", "% eligible cases", "Pathways identified and actually claimed"],
  ["EWS lead time", "before policy window", "Signal to human intervention, not a default prediction", "rbi.sma"],
  ["Rural cluster origination", "new-to-credit / anchor", "Surfaced per anchor sanction, with evidence path"],
  ["PSL sub-target movement", "percentage-point change", "Organic origination, not PSLC purchase"],
];

function ArchitectureNode({ label, detail, tone }: { label: string; detail: string; tone: "blue" | "violet" | "teal" }) {
  const styles = { blue: "border-blue-200 bg-blue-50 text-blue-950", violet: "border-violet-200 bg-violet-50 text-violet-950", teal: "border-teal-200 bg-teal-50 text-teal-950" };
  return <div className={`rounded border p-4 ${styles[tone]}`}><div className="text-xs font-bold uppercase tracking-widest opacity-70">{label}</div><div className="mt-2 text-sm font-bold">{detail}</div></div>;
}

export default function ClosePage() {
  return <Shell><div className="space-y-5">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-[.22em] accent-human">Close / the ask</div><h1 className="mt-2 max-w-4xl text-3xl font-bold tracking-tight sm:text-4xl">Keep the core. Close the intelligence loop.</h1><p className="mt-2 max-w-3xl text-slate-600">A small architecture change creates a large operating question: can the bank measure more evidence-backed decisions without moving the system of record?</p></div><div className="rounded bg-slate-950 px-4 py-3 text-right text-white"><div className="text-[10px] font-bold uppercase tracking-widest text-teal-300">Pilot shape</div><div className="mt-1 text-lg font-black">90 days · one state · one bank</div></div></header>
    <section className="card p-5"><div className="text-xs font-bold uppercase tracking-widest text-violet-700">Architecture loop</div><h2 className="mt-1 text-2xl font-bold">Understand above the core. Record back into the core.</h2><div className="mt-5 grid gap-2 lg:grid-cols-[1fr_34px_1fr_34px_1fr_34px_1fr_34px_1fr] lg:items-center"><ArchitectureNode label="Systems of record" detail="LOS · CBS · LMS · CRM" tone="blue" /><ArrowRight className="hidden justify-self-center text-slate-400 lg:block" /><ArchitectureNode label="Intelligence fabric" detail="Identity · evidence · policy · risk" tone="violet" /><ArrowRight className="hidden justify-self-center text-slate-400 lg:block" /><ArchitectureNode label="Agent workforce" detail="Research · CAM · EWS · cluster" tone="violet" /><ArrowRight className="hidden justify-self-center text-slate-400 lg:block" /><ArchitectureNode label="Human authority" detail="Challenge · approve · account" tone="teal" /><ArrowRight className="hidden justify-self-center text-slate-400 lg:block" /><ArchitectureNode label="Decision of record" detail="Sanction · CP · intervention" tone="blue" /></div><div className="mt-4 flex justify-center lg:hidden"><ArrowDown className="text-slate-400" /></div><div className="mt-4 rounded bg-slate-50 p-4 text-center text-sm font-semibold leading-6 text-slate-700">The core banking system records what happened. The intelligence layer understands what is happening, why, what could happen next, and what to investigate. The human decides. The architecture stays intact.</div></section>
    <section className="card overflow-hidden"><div className="border-b border-slate-200 bg-slate-50 p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-xs font-bold uppercase tracking-widest text-teal-700">One experiment, not an MoU</div><h2 className="mt-1 text-2xl font-bold">90 days to earn the right to scale</h2></div><span className="rounded-full bg-teal-100 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-teal-800">Stop / scale decision</span></div><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">One state · one bank · one product category · one AI credit workforce. Measure a baseline first, run the same work with the workforce, and let the bank’s own committee judge quality.</p></div><div className="grid gap-3 p-5 md:grid-cols-3"><div className="rounded border border-slate-200 bg-white p-4"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-slate-500"><CircleDot size={15} className="text-blue-700" />Days 1–15</div><div className="mt-3 font-bold">Instrument the baseline</div><p className="mt-1 text-xs leading-5 text-slate-600">Lock definitions, consent path, human authority, current TAT and fully-loaded cost.</p></div><div className="rounded border border-violet-200 bg-violet-50 p-4"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-violet-700"><CircleDot size={15} />Days 16–75</div><div className="mt-3 font-bold text-violet-950">Run the workforce</div><p className="mt-1 text-xs leading-5 text-violet-900">Shadow then operate on the selected product. Retain every conflict, correction and quality score.</p></div><div className="rounded border border-teal-200 bg-teal-50 p-4"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-teal-700"><CheckCircle2 size={15} />Days 76–90</div><div className="mt-3 font-bold text-teal-950">Committee verdict</div><p className="mt-1 text-xs leading-5 text-teal-900">Blind-score CAMs, review economics and decide: stop, adjust, or scale.</p></div></div></section>
    <section className="card overflow-hidden"><div className="border-b border-slate-200 p-5"><div className="text-xs font-bold uppercase tracking-widest text-slate-500">Pilot scorecard</div><h2 className="mt-1 text-2xl font-bold">Measure value without hiding the denominator</h2></div><div className="grid gap-px bg-slate-200 sm:grid-cols-2 lg:grid-cols-3">{metrics.map(([label, target, definition, factId]) => <div key={label} className="bg-white p-4"><div className="text-sm font-bold text-slate-950">{label}</div><div className="mt-2 tabnums text-sm font-black text-violet-800">{target}</div><p className="mt-1 text-xs leading-5 text-slate-600">{definition}</p>{factId ? <div className="mt-2 text-[10px] leading-4 text-slate-500"><Fact id={factId} /></div> : null}</div>)}</div></section>
    <section className="rounded bg-slate-950 p-6 text-xl font-bold leading-8 text-white sm:text-2xl"><div className="mb-3 text-xs uppercase tracking-[.2em] text-teal-300">The ask</div>If it creates no measurable value, we stop. If it does, we scale.</section>
  </div></Shell>;
}
