import { Fact } from "@/components/governance/Fact";
import { Shell } from "@/components/presenter/Shell";

const controls = [
  ["Board-approved MRM framework", "The demo exposes a named control register, human authority boundary and exception path; the bank owns the framework and approval.", "Bank MRM owner", "Mapped"],
  ["Independent validation", "Every model entry has a validation owner and date. Validation is separate from the agent builder, with adverse findings retained.", "Independent validation", "Mapped"],
  ["Mandatory human oversight for material decisions", "The facility slider is a logged human action. Conflict, sanction, fraud classification and limit movement cannot be completed by the model.", "Credit officer / committee", "Live boundary"],
  ["Explainability for customer-facing models", "Claims carry source, artefact, timestamp, transformation and confidence. The borrower view removes internal scores and jargon.", "Product + credit risk", "Mapped"],
  ["Disclosure that the user is interacting with AI", "The persistent workshop banner and borrower-facing copy disclose scripted AI behavior before a data pull or recommendation.", "Product owner", "Visible"],
  ["Third-party and vendor accountability", "The provenance surface records model, agent and vendor version. The regulated entity remains accountable for its LSP.", "RE / TSP governance", "Mapped"],
  ["Adversarial and edge-case testing", "The adversarial agent tries to prevent sanction; source conflict and stale land records are carried forward rather than smoothed.", "Model risk + credit", "Demonstrated"],
  ["Model inventory and versioning", "The live inventory below records purpose, owner, version, validation date and known failure mode, including the land-use retraction.", "Model risk office", "Visible"],
];

const inventory = [
  ["fabric-research", "0.9.3", "Research lead", "11 Aug 2026", "Missed or stale source; conflict is carried forward"],
  ["evidence-reconcile", "0.8.1", "Credit risk", "11 Aug 2026", "Cannot resolve 18.8% turnover variance without officer"],
  ["land-retrieval", "0.6.4", "Operations risk", "11 Aug 2026", "Stale district extract; retracted after later revenue record"],
  ["ews-reconciler", "0.7.0", "Portfolio risk", "11 Aug 2026", "False positive from isolated signal; assumption link required"],
  ["adversarial-credit", "0.4.2", "Independent validation", "11 Aug 2026", "May over-index on downside; cannot sanction"],
];

export default function GovernancePage() {
  return <Shell><div className="space-y-5">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-[.22em] accent-human">Close / governance</div><h1 className="mt-2 max-w-4xl text-3xl font-bold tracking-tight sm:text-4xl">Survive the inspection because the behavior is legible.</h1><p className="mt-2 max-w-3xl text-slate-600">The demo is not asking the room to trust a model. It maps each behavior to the operative draft MRM expectations and keeps the accountable human in the loop.</p></div><div className="max-w-sm rounded border border-amber-300 bg-amber-50 px-4 py-3 text-sm leading-5 text-amber-950"><b>Instrument status:</b> <Fact id="rbi.mrm.draft" /></div></header>
    <section className="card overflow-hidden"><div className="border-b border-slate-200 bg-slate-50 p-5"><div className="text-xs font-bold uppercase tracking-widest text-violet-700">Point-by-point mapping</div><h2 className="mt-1 text-2xl font-bold">Draft MRM guidance → demo behavior</h2><p className="mt-2 text-sm text-slate-600">Mapped means the product behavior is visible in this workshop. It does not mean a bank’s board framework or validation obligation has been discharged.</p></div><div className="divide-y divide-slate-100">{controls.map(([control, behavior, authority, status], index) => <div key={control} className="grid gap-3 p-4 lg:grid-cols-[28px_1fr_1.7fr_170px] lg:items-start"><div className="flex h-7 w-7 items-center justify-center rounded-full bg-violet-100 text-xs font-black text-violet-800">{index + 1}</div><div><div className="font-bold text-slate-950">{control}</div><div className="mt-1 text-xs font-semibold text-teal-700">ACCOUNTABLE · {authority}</div></div><p className="text-sm leading-6 text-slate-700">{behavior}</p><span className="w-fit rounded-full bg-emerald-100 px-2 py-1 text-[10px] font-bold uppercase tracking-widest text-emerald-800">{status}</span></div>)}</div></section>
    <section className="card overflow-hidden"><div className="border-b border-slate-200 p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-xs font-bold uppercase tracking-widest text-violet-700">Model risk register</div><h2 className="mt-1 text-2xl font-bold">Model and agent inventory</h2></div><span className="rounded-full bg-slate-100 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-slate-600">SIMULATED WORKSHOP REGISTER</span></div></div><div className="overflow-x-auto"><table className="w-full min-w-[830px] text-left text-sm"><thead className="border-b border-slate-300 bg-slate-50 text-[10px] uppercase tracking-widest text-slate-500"><tr><th className="px-5 py-3">Model / agent</th><th className="px-3 py-3">Version</th><th className="px-3 py-3">Owner</th><th className="px-3 py-3">Last validation</th><th className="px-3 py-3">Known failure mode</th></tr></thead><tbody>{inventory.map(([name, version, owner, date, failure]) => <tr key={name} className="border-b border-slate-100 last:border-0"><th className="px-5 py-3 font-semibold text-slate-900">{name}</th><td className="px-3 py-3 tabnums text-violet-800">{version}</td><td className="px-3 py-3 text-slate-600">{owner}</td><td className="px-3 py-3 tabnums text-slate-600">{date}</td><td className="px-3 py-3 text-xs leading-5 text-slate-600">{failure}</td></tr>)}</tbody></table></div><div className="border-t border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-950"><b>Retraction is an inventory event:</b> the land-use retrieval model’s stale assertion is not deleted. Its original claim, source, challenger, corrected source and downstream CP change remain in the audit trail.</div></section>
    <div className="grid gap-3 lg:grid-cols-2"><section className="card p-5"><div className="text-xs font-bold uppercase tracking-widest text-teal-700">Human authority</div><h2 className="mt-1 text-xl font-bold">AI recommends. The human decides.</h2><p className="mt-2 text-sm leading-6 text-slate-700">A model can surface a risk, draft a CAM or propose a pathway. It cannot move a credit limit, resolve a material conflict or classify fraud.</p><div className="mt-3 text-xs leading-5 text-teal-950"><Fact id="rbi.dl2025.limit" /><br /><Fact id="sc.rajeshagarwal" /></div></section><section className="card p-5"><div className="text-xs font-bold uppercase tracking-widest text-blue-700">TSP-neutral position</div><h2 className="mt-1 text-xl font-bold">Make the bank’s existing core intelligent.</h2><p className="mt-2 text-sm leading-6 text-slate-700">The next generation of TSP is not the company that replaces the bank’s core. It is the company that makes the bank’s existing core intelligent. This layer stays TSP-neutral.</p><div className="mt-3 rounded bg-blue-50 p-3 text-xs leading-5 text-blue-950"><Fact id="rbi.dl2025.lsp" /><br />That accountability is why provenance has to be a product surface, not a promise.</div></section></div>
    <section className="rounded bg-slate-950 p-5 text-lg font-bold leading-7 text-white">The bank does not outsource accountability by adding intelligence. It makes accountability inspectable at every hand-off.</section>
  </div></Shell>;
}
