"use client";

import { useEffect, useState } from "react";
import { AlertTriangle, ArrowRight, CheckCircle2, Eye, ShieldAlert } from "lucide-react";
import { Fact } from "@/components/governance/Fact";
import { ewsSignals } from "@/content/ews";

export function EwsPanel() {
  const [visible, setVisible] = useState(0);

  useEffect(() => {
    if (visible >= ewsSignals.length) return;
    const timer = window.setTimeout(() => setVisible((count) => Math.min(count + 1, ewsSignals.length)), 500);
    return () => window.clearTimeout(timer);
  }, [visible]);

  const complete = visible === ewsSignals.length;
  return <div className="space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-[.22em] accent-fabric">Portfolio / intelligence fabric</div><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">WOW 3 · Early warning while current</h1><p className="mt-2 max-w-3xl text-slate-600">The account is green in the LMS. The fabric reconciles operating signals against the assumptions that made the sanction safe, before the account moves through the overdue bands defined in <Fact id="rbi.sma" />.</p></div><button onClick={() => setVisible(ewsSignals.length)} className="inline-flex items-center gap-2 rounded border border-violet-300 bg-white px-4 py-2 text-sm font-bold text-violet-800 hover:bg-violet-50"><Eye size={16} /> Reveal all</button></div>
    <div className="grid gap-px overflow-hidden rounded border border-slate-200 bg-slate-200 md:grid-cols-2"><div className="min-h-[180px] bg-white p-5"><div className="text-xs font-bold uppercase tracking-widest text-slate-500">Traditional LMS</div><div className="mt-4 flex items-center gap-3"><CheckCircle2 className="text-emerald-600" size={25} /><div className="text-2xl font-black text-emerald-700">CURRENT</div></div><div className="mt-3 text-sm text-slate-600">0 DPD · payment honoured · nothing to see</div><div className="mt-5 rounded bg-slate-50 p-3 text-xs text-slate-600">A servicing status, not an operating-health diagnosis.</div></div><div className="min-h-[180px] bg-violet-50 p-5"><div className="text-xs font-bold uppercase tracking-widest text-violet-700">Intelligence fabric</div><div className="mt-4 flex items-center gap-3"><ShieldAlert className="text-red-600" size={25} /><div className="text-2xl font-black text-red-700">EARLY WARNING</div></div><div className="mt-3 text-sm text-violet-950">{complete ? "6 sanction assumptions challenged" : `${visible} of ${ewsSignals.length} signals reconciled`}</div><div className="mt-5 h-2 rounded-full bg-violet-200"><div className="h-2 rounded-full bg-violet-700 transition-all duration-300" style={{ width: `${(visible / ewsSignals.length) * 100}%` }} /></div></div></div>
    <section className="card overflow-hidden"><div className="border-b border-slate-200 bg-slate-50 p-4"><div className="flex items-center gap-2 text-sm font-bold"><ArrowRight size={17} className="text-violet-700" />Signal → sanction assumption reconciliation</div><p className="mt-1 text-xs text-slate-500">No score is substituted for a reason. Every alert names the assumption it violates and the next human action.</p></div><div className="space-y-3 p-4">{ewsSignals.map((signal, index) => { const revealed = index < visible; return <div key={signal.id} className={`min-h-[120px] rounded border p-4 transition-colors duration-300 ${revealed ? signal.severity === "red" ? "border-red-200 bg-red-50/60" : "border-amber-200 bg-amber-50/60" : "border-slate-200 bg-white"}`}><div className="grid gap-3 md:grid-cols-[1fr_auto_1.2fr] md:items-center"><div>{revealed ? <><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-2 py-1 text-[10px] font-bold uppercase tracking-widest ${signal.severity === "red" ? "bg-red-100 text-red-800" : "bg-amber-100 text-amber-800"}`}>{signal.severity} flag</span><span className="text-[10px] font-bold uppercase tracking-widest text-slate-500">SIMULATED</span></div><div className="mt-2 font-bold text-slate-950">{signal.label}</div><div className="mt-1 tabnums text-sm font-semibold">{signal.value}</div><div className="mt-2 text-xs text-slate-500">{signal.source} · {signal.artefact}</div></> : <div className="flex items-center gap-2 text-sm text-slate-400"><span className="h-2 w-2 rounded-full bg-slate-300" />Awaiting deterministic scan…</div>}</div><div className="hidden text-slate-300 md:block"><ArrowRight size={22} /></div><div className={revealed ? "" : "opacity-40"}><div className="text-[10px] font-bold uppercase tracking-widest text-violet-700">Sanction assumption</div><div className="mt-1 font-semibold text-slate-950">{signal.sanctionAssumption}</div><div className="mt-1 text-xs leading-5 text-red-800">{revealed ? signal.violation : "Reconciliation held until the source is read."}</div>{revealed && <div className="mt-2 text-xs font-bold text-teal-800">NEXT HUMAN ACTION · {signal.action}</div>}</div></div></div>; })}</div></section>
    <div className="grid gap-3 lg:grid-cols-[1.3fr_1fr]"><div className="rounded border border-red-300 bg-slate-950 p-5 text-white"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-red-300"><AlertTriangle size={15} /> Account state</div><div className="mt-3 text-2xl font-black">Red-flagged account · RM intervention recommended</div><p className="mt-2 text-sm leading-6 text-slate-300">This is not an NPA and not a default. It is intelligence before default, while the account remains in the current servicing band.</p><div className="mt-4 border-t border-slate-700 pt-3 text-xs leading-5 text-slate-300"><Fact id="rbi.sma" /> <Fact id="rbi.ews" /></div></div><div className="rounded border border-teal-200 bg-teal-50 p-5 text-sm leading-6 text-teal-950"><b>Human boundary</b><br />The model flags and explains. The relationship manager investigates. Only the bank decides what enters the account record.<div className="mt-3 text-xs"><Fact id="sc.rajeshagarwal" /></div></div></div>
  </div>;
}
