"use client";

import { AlertTriangle, CalendarClock, CheckCircle2, Droplets, Milk, ShieldCheck } from "lucide-react";
import { Fact } from "@/components/governance/Fact";

interface MilkMonth { month: string; litres: number; payment: string; ledgerMatches: boolean; }

const milkRecord: MilkMonth[] = ([
  ["Jun 24", 32, "Settled", true], ["Jul 24", 34, "Settled", true], ["Aug 24", 35, "Settled", true], ["Sep 24", 33, "Settled", true], ["Oct 24", 30, "Settled", true], ["Nov 24", 27, "Settled", true], ["Dec 24", 25, "Settled", true], ["Jan 25", 24, "Settled", true], ["Feb 25", 26, "Settled", true], ["Mar 25", 29, "Settled", true], ["Apr 25", 31, "Settled", true], ["May 25", 28, "Partial", false], ["Jun 25", 30, "Settled", true], ["Jul 25", 33, "Settled", true], ["Aug 25", 35, "Settled", true], ["Sep 25", 34, "Settled", true], ["Oct 25", 31, "Settled", true], ["Nov 25", 27, "Settled", true], ["Dec 25", 24, "Settled", true], ["Jan 26", 25, "Settled", true], ["Feb 26", 27, "Settled", true], ["Mar 26", 30, "Settled", true], ["Apr 26", 32, "Settled", true], ["May 26", 29, "Partial", false], ["Jun 26", 31, "Settled", true], ["Jul 26", 33, "Settled", true]
] as const).map(([month, litres, payment, ledgerMatches]) => ({ month, litres, payment, ledgerMatches }));

export function LakshmiCase() {
  return <div className="space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-[.22em] accent-human">Portfolio / ticket-size proof</div><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Lakshmi Devi G. · dairy case</h1><p className="mt-2 max-w-3xl text-slate-600">The same fabric, applied to a ₹1.60 lakh request in Gudupalle. No bureau file is not the same thing as no evidence.</p></div><div className="rounded-full bg-teal-100 px-4 py-2 text-xs font-bold uppercase tracking-widest text-teal-800">New to credit · simulated</div></div>
    <div className="grid gap-3 md:grid-cols-4"><Info label="Borrower" value="Lakshmi Devi G." detail="38 · Gudupalle" /><Info label="Request" value="₹1.60 lakh" detail="KCC-AH + investment credit" /><Info label="Livestock" value="3 crossbred cows" detail="Chaff cutter + feed" /><Info label="Bureau" value="No file" detail="New to credit" /></div>
    <section className="card overflow-hidden"><div className="flex flex-wrap items-end justify-between gap-3 border-b border-slate-200 bg-slate-50 p-4"><div><div className="flex items-center gap-2 text-sm font-bold"><Milk size={17} className="text-teal-700" />26-month milk-society pouring record</div><p className="mt-1 text-xs text-slate-500">Seasonality stays visible. The model does not flatten a real production cycle into a monthly average.</p></div><span className="rounded-full bg-slate-200 px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-slate-600">26 observations · simulated</span></div><div className="grid grid-cols-2 gap-2 p-4 sm:grid-cols-4 lg:grid-cols-[repeat(13,minmax(0,1fr))]">{milkRecord.map((entry) => <div key={entry.month} className={`min-h-[92px] rounded border p-2 ${entry.ledgerMatches ? "border-slate-200 bg-white" : "border-red-300 bg-red-50"}`}><div className="text-[10px] font-bold text-slate-500">{entry.month}</div><div className="mt-3 flex items-end gap-1"><Droplets size={13} className={entry.ledgerMatches ? "text-teal-600" : "text-red-600"} /><span className="tabnums text-lg font-bold">{entry.litres}</span></div><div className="text-[10px] text-slate-500">litres/day</div><div className={`mt-2 text-[10px] font-bold ${entry.ledgerMatches ? "text-emerald-700" : "text-red-700"}`}>{entry.payment}</div></div>)}</div></section>
    <div className="grid gap-3 lg:grid-cols-[1.1fr_1fr]"><section className="rounded border border-amber-300 bg-amber-50 p-5"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-amber-800"><AlertTriangle size={15} />Conflict carried forward</div><h2 className="mt-3 text-2xl font-bold text-amber-950">Two months do not reconcile</h2><p className="mt-2 text-sm leading-6 text-amber-950">The pouring record and society payment ledger disagree in May 2025 and May 2026. The fabric flags the mismatch rather than smoothing it into an approval.</p><div className="mt-4 grid grid-cols-2 gap-2 text-xs font-semibold text-amber-900"><div className="rounded border border-amber-200 bg-white/60 p-3">Pouring record<br /><b>Present</b></div><div className="rounded border border-red-300 bg-red-100 p-3">Payment ledger<br /><b>Partial</b></div></div></section><section className="rounded border border-teal-300 bg-teal-50 p-5"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-teal-800"><CheckCircle2 size={15} />Evidence-backed recommendation</div><div className="mt-3 text-3xl font-black text-teal-950">₹1.60 lakh</div><p className="mt-2 text-sm leading-6 text-teal-950">Recommend subject to a human review of the two flagged settlements, with repayment aligned to milk payment cycles.</p><div className="mt-4 text-xs leading-5 text-teal-950"><Fact id="kcc.subvention" /></div></section></div>
    <section className="card p-5"><div className="flex items-center gap-2 text-sm font-bold"><CalendarClock size={18} className="text-teal-700" />Repayment follows the milk cycle, not calendar EMIs</div><div className="mt-4 grid gap-3 md:grid-cols-3"><Repayment label="Society settlement" detail="Deduct / collect when the milk payment lands" /><Repayment label="Low-output months" detail="Use the visible seasonal trough to size the buffer" /><Repayment label="Human exception" detail="Hold the two mismatched settlements for review" /></div><div className="mt-4 rounded border border-slate-200 bg-slate-50 p-4 text-xs leading-5 text-slate-700"><ShieldCheck className="mr-1 inline-block text-teal-700" size={14} />Collateral context: <Fact id="agri.collateralfree" /></div></section>
    <div className="rounded bg-slate-950 p-6 text-xl font-bold leading-8 text-white sm:text-2xl">No bank in this room can afford four hours of a credit officer&apos;s time on a ₹1.6 lakh loan. That is not a values problem. It is an arithmetic problem. This changes the arithmetic.</div>
  </div>;
}

function Info({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="card p-4"><div className="text-xs font-bold uppercase tracking-widest text-slate-500">{label}</div><div className="mt-2 text-lg font-bold">{value}</div><div className="mt-1 text-xs text-slate-600">{detail}</div></div>; }
function Repayment({ label, detail }: { label: string; detail: string }) { return <div className="rounded border border-teal-200 bg-teal-50 p-4"><div className="font-bold text-teal-950">{label}</div><div className="mt-1 text-sm leading-5 text-teal-900">{detail}</div></div>; }
