"use client";

import Link from "next/link";
import {useDeferredValue, useState} from "react";
import {AlertCircle, ArrowRight, Filter, Search, Users} from "lucide-react";
import {Fact} from "@/components/governance/Fact";
import {clusterMandals, clusterNodes, type ClusterMandal} from "@/content/cluster";
import {useProductStore} from "@/lib/product-store";

type Qualification="qualified"|"unresolved"|"all";
const names=["Ravi Kumar","Saraswati N.","Anjaneya Reddy","Muneer Basha","Padmavathi K.","Ramesh Naidu","Jyothi M.","Narasimha G.","Sujatha R.","Venkatesh P."];

export function ClusterWorkbench() {
  const reviewed=useProductStore(state=>state.clusterReviewed);
  const act=useProductStore(state=>state.act);
  const [query,setQuery]=useState("");
  const [mandal,setMandal]=useState<ClusterMandal|"All">("All");
  const [qualification,setQualification]=useState<Qualification>("qualified");
  const deferredQuery=useDeferredValue(query.trim().toLowerCase());
  const rows=clusterNodes.map((node,index)=>({...node,name:node.id==="gudupalle-001"?"Lakshmi Devi G.":names[index%names.length],requestLakh:node.id==="gudupalle-001"?1.6:Number((1.2+(index%9)*.11).toFixed(2))}));
  const filtered=rows.filter(row=>(mandal==="All"||row.mandal===mandal)&&(qualification==="all"||(qualification==="qualified"?row.evidenceable:!row.evidenceable))&&(!deferredQuery||`${row.name} ${row.id} ${row.evidenceSource}`.toLowerCase().includes(deferredQuery)));
  const lakshmi=rows.find(row=>row.id==="gudupalle-001")!;
  const visible=[...filtered].sort((a,b)=>Number(b.id===lakshmi.id)-Number(a.id===lakshmi.id)).slice(0,18);
  const review=()=>act("Lakshmi Devi alternate-evidence case opened from Annapurna cluster",{clusterReviewed:true});
  return <div className="space-y-4 pb-16 lg:pb-0">
    <header className="rounded-lg border border-slate-300 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-[10px] font-black uppercase tracking-[.16em] text-violet-700">Cluster origination · workbench</div><h1 className="mt-2 text-2xl font-black tracking-tight">Annapurna procurement network</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Supplier records are matched to available evidence for review. Evidence qualification places a prospect in the queue; it is not an underwriting decision, eligibility finding or offer.</p></div><span className="rounded bg-slate-100 px-3 py-2 text-[10px] font-black uppercase tracking-wider text-slate-600">As of 11 Aug 2026 · Simulated</span></div></header>

    <section className="grid gap-px overflow-hidden rounded-lg border border-slate-300 bg-slate-200 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Supplier records" value="312" detail="Procurement ledger"/><Metric label="Evidence-qualified" value="287" detail="Review queue only" tone="green"/><Metric label="Unresolved" value="25" detail="No inferred approval" tone="amber"/><Metric label="Indicated requests" value="₹4.68 Cr" detail="Not sanctioned"/><Metric label="Women" value="171" detail="Qualified records"/></section>

    <section className="rounded-lg border border-slate-300 bg-white"><div className="border-b border-slate-200 p-4"><div className="flex flex-wrap items-center gap-3"><div className="flex min-w-[220px] flex-1 items-center gap-2 rounded-md border border-slate-300 bg-white px-3 py-2"><Search size={15} className="text-slate-400"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search prospect, supplier ID or evidence" className="w-full bg-transparent text-xs outline-none"/></div><label className="flex items-center gap-2 text-xs font-bold text-slate-600"><Filter size={14}/><select value={mandal} onChange={event=>setMandal(event.target.value as ClusterMandal|"All")} className="rounded-md border border-slate-300 bg-white px-3 py-2 text-xs font-semibold"><option>All</option>{clusterMandals.map(item=><option key={item}>{item}</option>)}</select></label><select value={qualification} onChange={event=>setQualification(event.target.value as Qualification)} className="rounded-md border border-slate-300 bg-white px-3 py-2 text-xs font-semibold"><option value="qualified">Evidence-qualified</option><option value="unresolved">Unresolved</option><option value="all">All records</option></select></div><div className="mt-3 flex flex-wrap items-center justify-between gap-2 text-[10px] text-slate-500"><span>{filtered.length} records match · showing up to 18</span><span>Qualification based on retrievable evidence, not credit approval</span></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[970px] text-left text-xs"><thead className="border-b border-slate-200 bg-slate-50 text-[9px] uppercase tracking-wider text-slate-500"><tr><th className="px-4 py-3">Prospect</th><th className="px-3 py-3">Mandal</th><th className="px-3 py-3">Evidence</th><th className="px-3 py-3">Profile</th><th className="px-3 py-3">Indicated request</th><th className="px-3 py-3">Queue status</th><th className="px-4 py-3 text-right">Action</th></tr></thead><tbody>{visible.map(row=>{const isLakshmi=row.id===lakshmi.id; return <tr key={row.id} className={`border-b border-slate-100 ${isLakshmi?"bg-violet-50/70":""}`}><td className="px-4 py-3"><div className="font-black text-slate-900">{row.name}</div><div className="mt-1 font-mono text-[10px] text-slate-500">{row.id}</div></td><td className="px-3 py-3">{row.mandal}</td><td className="px-3 py-3"><div className="font-semibold">{row.evidenceSource}</div>{!row.evidenceable?<div className="mt-1 max-w-48 text-[10px] text-amber-800">{row.counterfactualReason}</div>:null}</td><td className="px-3 py-3"><div>{row.newToCredit?"New to credit":"Bureau footprint"}</div><div className="mt-1 text-[10px] text-slate-500">{row.woman?"Woman applicant":"Individual applicant"}</div></td><td className="px-3 py-3 font-mono font-bold">₹{row.requestLakh.toFixed(2)} lakh</td><td className="px-3 py-3">{row.evidenceable?<span className="rounded bg-emerald-100 px-2 py-1 text-[9px] font-black uppercase tracking-wider text-emerald-800">Evidence-qualified</span>:<span className="rounded bg-amber-100 px-2 py-1 text-[9px] font-black uppercase tracking-wider text-amber-800">Unresolved</span>}</td><td className="px-4 py-3 text-right">{isLakshmi?<Link href="/2/leads/lakshmi" onClick={review} className="inline-flex items-center gap-1 rounded-md bg-slate-950 px-3 py-2 text-[10px] font-black text-white">{reviewed?"Continue review":"Review evidence"}<ArrowRight size={13}/></Link>:<button type="button" disabled={!row.evidenceable} className="rounded-md border border-slate-300 px-3 py-2 text-[10px] font-bold text-slate-600 disabled:cursor-not-allowed disabled:opacity-40">Review</button>}</td></tr>})}</tbody></table></div>
      {visible.length===0?<div className="p-8 text-center text-sm text-slate-500">No records match the selected filters.</div>:null}
    </section>

    <section className="grid gap-4 lg:grid-cols-[1fr_1.2fr]"><div className="rounded-lg border border-amber-300 bg-amber-50 p-4"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-wider text-amber-800"><AlertCircle size={15}/>25 unresolved records</div><p className="mt-2 text-sm leading-6 text-amber-950">Missing digitised land records, absent AA consent, or tenancy without a record of rights remains visible. These records are held for evidence resolution and excluded from the 287-record review queue.</p><div className="mt-2 text-xs text-amber-900"><Fact id="uli.adoption"/></div></div><div className="rounded-lg border border-slate-300 bg-white p-4"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-wider text-slate-600"><Users size={15}/>Queue boundary</div><p className="mt-2 text-sm leading-6 text-slate-700">Review opens alternate evidence and repayment design. Conversion occurs only when an officer creates an application; appraisal, KYC, eligibility, borrower consent and credit decision remain downstream controls.</p></div></section>
  </div>;
}

function Metric({label,value,detail,tone="base"}:{label:string;value:string;detail:string;tone?:"base"|"green"|"amber"}) {const colors=tone==="green"?"text-emerald-800":tone==="amber"?"text-amber-800":"text-slate-950"; return <div className="bg-white p-4"><div className="text-[9px] font-black uppercase tracking-wider text-slate-400">{label}</div><div className={`mt-1 font-mono text-xl font-black ${colors}`}>{value}</div><div className="mt-1 text-[10px] text-slate-500">{detail}</div></div>}
