"use client";

import Link from "next/link";
import {AlertTriangle, ArrowLeft, Check, CircleGauge, UserCheck} from "lucide-react";
import {Fact} from "@/components/governance/Fact";
import {ewsSignals} from "@/content/ews";
import {useProductStore} from "@/lib/product-store";

export function EarlyWarningWorkspace() {
  const assigned=useProductStore(state=>state.ewsAssigned);
  const act=useProductStore(state=>state.act);
  const assign=()=>act("RM investigation assigned to S. Reddy for LAN 03417",{ewsAssigned:true});
  return <div className="space-y-4 pb-16 lg:pb-0">
    <div className="flex flex-wrap items-center justify-between gap-3"><Link href="/2/accounts/03417" className="inline-flex items-center gap-2 text-xs font-bold text-slate-600 hover:text-slate-950"><ArrowLeft size={14}/>Account MSME/AP/2026/03417</Link><span className="rounded bg-emerald-50 px-2 py-1 text-[10px] font-black uppercase tracking-wider text-emerald-800">LMS status · Current · 0 DPD</span></div>
    <header className="rounded-lg border border-slate-300 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-5"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.16em] text-red-700"><CircleGauge size={15}/>Operational triage</div><h1 className="mt-2 text-2xl font-black tracking-tight">Early-warning review · Sri Annapurna Foods</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Six observed signals are reconciled to the assumptions that supported sanction. This review does not classify default or fraud; it creates an investigation task for the relationship manager.</p></div><button type="button" onClick={assign} disabled={assigned} className={`inline-flex items-center gap-2 rounded-md px-4 py-2.5 text-xs font-black ${assigned?"cursor-default bg-emerald-100 text-emerald-800":"bg-slate-950 text-white hover:bg-slate-800"}`}>{assigned?<><Check size={15}/>Assigned to S. Reddy</>:<><UserCheck size={15}/>Assign RM investigation</>}</button></div></header>

    <section className="grid gap-px overflow-hidden rounded-lg border border-slate-300 bg-slate-200 sm:grid-cols-2 xl:grid-cols-4"><TriageMetric label="Signals" value="6" detail="4 red · 2 amber"/><TriageMetric label="Assumptions challenged" value="6" detail="Reconciliation required"/><TriageMetric label="Servicing band" value="Current" detail="No missed payment"/><TriageMetric label="Task status" value={assigned?"Assigned":"Unassigned"} detail={assigned?"S. Reddy · due 13 Aug":"RM owner required"}/></section>

    <section className="overflow-hidden rounded-lg border border-slate-300 bg-white"><div className="border-b border-slate-200 bg-slate-50 px-4 py-3"><h2 className="text-sm font-black">Signal-to-assumption reconciliation</h2><p className="mt-1 text-xs text-slate-500">Every signal retains its source artefact, challenged assumption and required investigation.</p></div><div className="divide-y divide-slate-100">{ewsSignals.map(signal=><article key={signal.id} className="grid gap-3 p-4 lg:grid-cols-[1fr_1.1fr_1fr]"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded px-2 py-1 text-[9px] font-black uppercase tracking-wider ${signal.severity==="red"?"bg-red-100 text-red-800":"bg-amber-100 text-amber-800"}`}>{signal.severity}</span><span className="text-[10px] font-bold text-slate-400">SIMULATED OBSERVATION</span></div><h3 className="mt-2 text-sm font-black">{signal.label}</h3><p className="mt-1 font-mono text-xs font-bold text-slate-700">{signal.value}</p><p className="mt-2 text-[10px] text-slate-500">{signal.source} · {signal.artefact}</p></div><div className="border-l-2 border-violet-200 pl-3"><div className="text-[9px] font-black uppercase tracking-wider text-violet-700">Sanction assumption</div><p className="mt-1 text-xs font-semibold leading-5 text-slate-900">{signal.sanctionAssumption}</p><p className="mt-1 text-xs leading-5 text-red-800">{signal.violation}</p></div><div className="rounded-md border border-slate-200 bg-slate-50 p-3"><div className="text-[9px] font-black uppercase tracking-wider text-slate-500">Investigation action</div><p className="mt-1 text-xs font-semibold leading-5">{signal.action}</p></div></article>)}</div></section>

    <section className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><div className="rounded-lg border border-red-300 bg-red-50 p-4"><div className="flex items-center gap-2 text-xs font-black uppercase tracking-wider text-red-800"><AlertTriangle size={15}/>Triage outcome</div><h2 className="mt-2 text-lg font-black text-red-950">RM investigation required while account remains current</h2><p className="mt-1 text-sm leading-6 text-red-900">Credit should re-spread current turnover, establish the position of the fresh charge, validate buyer concentration and record the GST explanation. A human records any account action after investigation.</p></div><div className="rounded-lg border border-slate-300 bg-white p-4 text-xs leading-5 text-slate-700"><div className="font-black text-slate-950">Regulatory context</div><div className="mt-2 space-y-2"><div><Fact id="rbi.ews"/></div><div><Fact id="rbi.sma"/></div></div></div></section>
  </div>;
}

function TriageMetric({label,value,detail}:{label:string;value:string;detail:string}) {return <div className="bg-white p-4"><div className="text-[9px] font-black uppercase tracking-wider text-slate-400">{label}</div><div className="mt-1 font-mono text-xl font-black">{value}</div><div className="mt-1 text-[10px] text-slate-500">{detail}</div></div>}
