import Link from "next/link";
import { Fact } from "@/components/governance/Fact";
import { Shell } from "@/components/presenter/Shell";

const layers = [{ title: "SYSTEMS OF RECORD", text: "LOS · CBS · LMS · CRM", tone: "border-blue-300 bg-blue-50 text-blue-900" }, { title: "INTELLIGENCE FABRIC", text: "Identity  ·  Evidence  ·  Knowledge  ·  Policy  ·  Reasoning  ·  Risk  ·  Research", tone: "border-violet-300 bg-violet-50 text-violet-950" }, { title: "AGENT WORKFORCE", text: "Credit  ·  Project  ·  Policy  ·  Risk  ·  Fraud  ·  Adversarial", tone: "border-emerald-300 bg-emerald-50 text-emerald-950" }, { title: "HUMAN AUTHORITY", text: "Officer  ·  committee  ·  accountable decision-of-record", tone: "border-teal-300 bg-teal-50 text-teal-950" }];
const vocabulary = [["An LLM", "interprets"], ["A tool", "acts"], ["A policy engine", "decides the rules — deterministic, not an LLM"], ["An agent", "pursues an objective across steps"], ["A workflow", "controls the sequence"], ["An evidence engine", "proves provenance"], ["A human", "holds accountability"]];

export default function Fabric() { return <Shell><div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-[.22em] accent-human">Frame / 03 · architecture contract</div><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">The intelligence fabric</h1><p className="mt-2 max-w-3xl text-slate-600">Reliability comes from the architecture, not the model. Each layer has a job, a boundary and a visible owner.</p></div><Link href="/borrower/intent" className="rounded bg-blue-700 px-4 py-2 text-sm font-bold text-white hover:bg-blue-800">Enter the case →</Link></div>
    <div className="card p-5 sm:p-7"><div className="mx-auto max-w-4xl space-y-2">{layers.map((layer, index)=><div key={layer.title}><div className={`rounded-lg border-2 px-5 py-4 ${layer.tone}`}><div className="text-xs font-bold tracking-[.2em]">{layer.title}</div><div className="mt-2 text-base font-semibold sm:text-lg">{layer.text}</div></div>{index < layers.length - 1 && <div className="flex h-8 items-center justify-center"><span className="text-2xl text-slate-300">↑</span></div>}</div>)}<div className="mt-5 flex items-center justify-center gap-3 rounded border border-slate-200 bg-slate-50 p-3 text-center text-sm font-bold text-slate-700"><span>Decision-of-record</span><span className="text-teal-700">↔</span><span>flows back to the system of record</span></div></div></div>
    <div className="grid gap-4 lg:grid-cols-[1.1fr_.9fr]"><div className="card p-5"><div className="text-xs font-bold uppercase tracking-widest text-violet-700">Vocabulary discipline</div><div className="mt-4 divide-y divide-slate-100">{vocabulary.map(([term, meaning])=><div className="grid grid-cols-[minmax(110px,.45fr)_1fr] gap-4 py-3 text-sm" key={term}><span className="font-bold text-slate-800">{term}</span><span className="text-slate-600">{meaning}</span></div>)}</div></div><div className="space-y-4"><div className="card border-l-4 border-l-teal-600 p-5"><div className="text-xs font-bold uppercase tracking-widest text-teal-700">Accountability stays human</div><p className="mt-3 text-sm leading-6 text-slate-700">AI can surface evidence, recommend a path and expose a conflict. It cannot silently move a limit or turn a recommendation into a sanction.</p><p className="mt-3 text-sm leading-6 text-slate-700"><Fact id="rbi.dl2025.limit" /></p></div><div className="card border-l-4 border-l-amber-500 p-5"><div className="text-xs font-bold uppercase tracking-widest text-amber-700">Governance is part of the UI</div><p className="mt-3 text-sm leading-6 text-slate-700"><Fact id="rbi.mrm.draft" /></p></div></div></div>
    <div className="rounded-lg border border-slate-300 bg-slate-900 p-5 text-base font-semibold leading-7 text-white">The architecture stays legible under pressure: source systems record what happened; the fabric explains what is happening and what to investigate; the human decides.</div>
  </div></Shell>; }
