"use client";

import { useDemoStore } from "@/lib/store";
import { Fact } from "@/components/governance/Fact";
import { CbsAccountMaster } from "@/components/bank/CbsAccountMaster";
import { Shell } from "@/components/presenter/Shell";

const baseConditions = ["Executed sanction and facility documents", "Insurance and security documentation complete", "Raw-material escalation clause accepted", "CEFPPC sanction letter attached before subsidy-linked drawdown"];

export default function Sanction03417Page() {
  const retracted = useDemoStore(s => s.retracted);
  const conditions = retracted ? [...baseConditions.slice(0, 2), "Land-use conversion for survey 214/2B complete and verified", ...baseConditions.slice(2)] : baseConditions;
  return <Shell><div className="space-y-5"><div><div className="text-xs font-bold uppercase tracking-[.22em] accent-bank">Bank / sanction control</div><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">From CAM to the ledger</h1><p className="mt-2 max-w-3xl text-slate-600">One decision event routed through delegation, sanction conditions, CBS and a plain-language borrower offer.</p></div><div className="grid gap-3 lg:grid-cols-3"><div className="card p-4"><div className="text-xs font-bold uppercase tracking-widest text-slate-500">CAM summary</div><div className="mt-3 tabnums text-2xl font-bold">₹3.25 Cr TL</div><div className="mt-2 text-sm text-slate-600">+ ₹0.50 Cr working capital · proceed subject to CPs</div></div><div className="card border-blue-200 bg-blue-50 p-4"><div className="text-xs font-bold uppercase tracking-widest text-blue-700">DoP routing</div><div className="mt-3 text-lg font-bold text-blue-950">RCPC · one-up authority</div><div className="mt-2 text-sm text-blue-900">Projected-turnover deviation routes above the recommending officer.</div></div><div className="card border-amber-200 bg-amber-50 p-4"><div className="text-xs font-bold uppercase tracking-widest text-amber-800">Decision state</div><div className="mt-3 text-lg font-bold text-amber-950">{retracted ? "CP list corrected" : "Pending governed review"}</div><div className="mt-2 text-sm text-amber-900">{retracted ? "Retraction propagated from correction." : "Complete the correction flow to add the land-use CP."}</div></div></div><div className="card p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-xs font-bold uppercase tracking-widest text-teal-700">Conditions precedent</div><h2 className="mt-1 text-xl font-bold">Disbursement gate · {conditions.length} conditions</h2></div><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-900">FIRST DISBURSEMENT BLOCKED</span></div><div className="mt-4 grid gap-2 md:grid-cols-2">{conditions.map((condition, index) => <div key={condition} className={`flex items-start gap-3 rounded border p-3 text-sm ${retracted && index === 2 ? "border-red-300 bg-red-50 text-red-950" : "border-slate-200 bg-slate-50 text-slate-700"}`}><span className="tabnums text-xs font-bold text-slate-500">CP {index + 1}</span><span className="font-semibold">{condition}</span></div>)}</div>{retracted && <div className="mt-4 rounded border border-amber-300 bg-amber-50 p-3 text-sm text-amber-950"><b>Subsidy timeline shifted.</b> The grant claim cannot rely on the earlier land-use assertion; evidence must follow the corrected record.</div>}</div><CbsAccountMaster /><BorrowerOffer retracted={retracted} /></div></Shell>;
}

function BorrowerOffer({ retracted }: { retracted: boolean }) { return <section className="card overflow-hidden"><div className="border-b border-slate-200 bg-white p-5"><div className="text-xs font-bold uppercase tracking-widest text-fabric">Borrower view · KFS-style offer</div><h2 className="mt-1 text-2xl font-bold">Your next steps, without internal jargon</h2><p className="mt-2 max-w-2xl text-sm text-slate-600">A borrower-facing rendering of the same sanction event. The first disbursement remains subject to conditions precedent.</p></div><div className="grid gap-4 p-5 lg:grid-cols-[1fr_1fr]"><div className="space-y-3"><OfferRow label="Sanctioned amount" value="₹3.25 Cr term loan + ₹0.50 Cr WC" /><OfferRow label="Indicative annual rate" value="EBLR + 2.40% = 9.90%" /><OfferRow label="All-in charges" value="Shown in the final KFS before acceptance" /><OfferRow label="Offer state" value={retracted ? "Awaiting corrected land-use evidence" : "Awaiting document completion"} /></div><div className="rounded border border-blue-200 bg-blue-50 p-4 text-sm text-blue-950"><div className="text-xs font-bold uppercase tracking-widest text-blue-700">Your next four steps</div><ol className="mt-3 space-y-3">{["Review the offer and final KFS", "Submit the listed project and security documents", "Complete land-use and approval conditions", "Receive a disbursement schedule after CP clearance"].map((step, index) => <li key={step} className="flex gap-3"><span className="tabnums font-bold">0{index + 1}</span><span>{step}</span></li>)}</ol><div className="mt-4 border-t border-blue-200 pt-3 text-xs leading-5"><Fact id="rbi.dl2025.kfs" /></div></div></div></section>; }
function OfferRow({ label, value }: { label: string; value: string }) { return <div className="flex flex-wrap justify-between gap-3 border-b border-slate-100 pb-3 text-sm"><span className="text-slate-500">{label}</span><b className="text-right text-slate-950">{value}</b></div>; }
