"use client";

import { useState } from "react";
import { stress } from "@/lib/credit";

interface ToggleProps { label: string; checked: boolean; onChange: () => void; }

export function StressPanel() {
  const [revenueStress, setRevenueStress] = useState(false);
  const [materialStress, setMaterialStress] = useState(false);
  const [grantDelayed, setGrantDelayed] = useState(false);
  const result = stress({ facilityCr: 3.25, revenueStress, materialStress, grantDelayed });
  return <section className="card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-xs font-bold uppercase tracking-widest text-violet-700">Pure function stress runner</div><h3 className="mt-1 text-lg font-bold">Change the case, not the narrative</h3></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${result.policyPass ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{result.policyPass ? "ABOVE FLOOR" : "BELOW FLOOR"}</span></div><div className="mt-4 grid gap-2 md:grid-cols-3"><Toggle label="Revenue −15%" checked={revenueStress} onChange={() => setRevenueStress(value => !value)} /><Toggle label="Raw material +10%" checked={materialStress} onChange={() => setMaterialStress(value => !value)} /><Toggle label="CEFPPC grant delayed 12 months" checked={grantDelayed} onChange={() => setGrantDelayed(value => !value)} /></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[620px] text-right text-sm"><thead className="border-b border-slate-200 text-[10px] uppercase tracking-widest text-slate-500"><tr><th className="px-2 py-2 text-left">Projection year</th><th className="px-2 py-2">Revenue</th><th className="px-2 py-2">EBITDA</th><th className="px-2 py-2">Debt service</th><th className="px-2 py-2">DSCR</th></tr></thead><tbody>{result.years.map(year => <tr key={year.year} className="border-b border-slate-100"><th className="px-2 py-2 text-left font-semibold">Year {year.year}</th><td className="tabnums px-2 py-2">₹{year.revenueCr.toFixed(2)} Cr</td><td className="tabnums px-2 py-2">₹{year.ebitdaCr.toFixed(2)} Cr</td><td className="tabnums px-2 py-2">₹{year.debtServiceCr.toFixed(2)} Cr</td><td className={`tabnums px-2 py-2 font-bold ${year.dscr < 1.25 ? "text-red-700" : "text-emerald-700"}`}>{year.dscr.toFixed(2)}×</td></tr>)}</tbody></table></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded bg-slate-950 p-3 text-white"><div className="text-[10px] uppercase tracking-widest text-slate-400">Minimum DSCR</div><div className="mt-1 tabnums text-xl font-bold">{result.minDscr.toFixed(2)}×</div></div><div className="rounded border border-amber-200 bg-amber-50 p-3 text-amber-950"><div className="text-[10px] uppercase tracking-widest text-amber-700">Funding gap</div><div className="mt-1 tabnums text-xl font-bold">₹{result.fundingGapCr.toFixed(2)} Cr</div></div></div></section>;
}

function Toggle({ label, checked, onChange }: ToggleProps) { return <button aria-pressed={checked} onClick={onChange} className={`flex min-h-[48px] items-center justify-between gap-3 rounded border p-3 text-left text-sm font-bold ${checked ? "border-violet-400 bg-violet-50 text-violet-950" : "border-slate-200 bg-white text-slate-700"}`}><span>{label}</span><span className={`h-5 w-9 rounded-full p-0.5 ${checked ? "bg-violet-700" : "bg-slate-300"}`}><span className={`block h-4 w-4 rounded-full bg-white transition-transform ${checked ? "translate-x-4" : "translate-x-0"}`} /></span></button>; }
