import Link from "next/link";
import { Fact } from "@/components/governance/Fact";
import { Shell } from "@/components/presenter/Shell";

const rows = [["Data access", "service catalogue + consented pulls", "bank-owned integrations", "one view across sources"], ["Consent", "access rail, not decision authority", "purpose + borrower record", "consent artefact beside evidence"], ["Cross-source reconciliation", "outside the rail", "manual / fragmented", "conflict is surfaced, never smoothed"], ["Policy interpretation", "not the rail's job", "rulebook + credit policy", "deterministic policy layer"], ["Evidence / provenance", "service metadata", "documents and audit trail", "claim → source → transformation"], ["Credit reasoning", "not the rail's job", "credit officer / committee", "agents recommend; people decide"], ["Post-sanction monitoring", "new signals", "LMS / CBS views", "assumption-linked early warning"]];

export default function Rails() { return <Shell><div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-[.22em] accent-fabric">Frame / 02 · boundary map</div><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Rails solve access. What solves understanding?</h1><p className="mt-2 max-w-3xl text-slate-600">The intelligence fabric is complementary by construction: every new data service becomes a better signal for the layer above.</p></div><Link href="/frame/fabric" className="rounded border border-slate-300 bg-white px-4 py-2 text-sm font-bold hover:border-violet-400">Next: fabric →</Link></div>
    <div className="grid gap-3 md:grid-cols-3"><div className="card border-l-4 border-l-blue-600 p-5"><div className="text-xs font-bold uppercase tracking-widest text-blue-700">ULI / rails</div><div className="mt-3 text-xl font-bold">Reach</div><p className="mt-2 text-sm leading-6 text-slate-600"><Fact id="uli.scale" /></p><p className="mt-3 text-sm leading-6 text-slate-600"><Fact id="uli.scope" /></p></div><div className="card border-l-4 border-l-slate-400 p-5"><div className="text-xs font-bold uppercase tracking-widest text-slate-500">Bank stack</div><div className="mt-3 text-xl font-bold">Control</div><p className="mt-2 text-sm leading-6 text-slate-600">Owns the customer relationship, consent management, policy and credit decision.</p><p className="mt-3 text-sm leading-6 text-slate-600">The hard work is often between systems, not inside one system.</p></div><div className="card border-l-4 border-l-violet-600 p-5"><div className="text-xs font-bold uppercase tracking-widest text-violet-700">Intelligence fabric</div><div className="mt-3 text-xl font-bold">Understanding</div><p className="mt-2 text-sm leading-6 text-slate-600">Reconciles signals, carries uncertainty forward and makes the human decision better prepared.</p><p className="mt-3 text-sm leading-6 text-slate-600">Not a core replacement. A layer above.</p></div></div>
    <div className="card overflow-hidden"><div className="overflow-x-auto"><table className="min-w-[780px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-widest text-slate-500"><tr><th className="p-4">Capability</th><th className="p-4">ULI / rails</th><th className="p-4">Bank stack</th><th className="p-4 text-violet-800">Fabric</th></tr></thead><tbody>{rows.map(row=><tr className="border-t border-slate-100" key={row[0]}>{row.map((cell, i)=><td className={`p-4 leading-6 ${i===0?"font-bold text-slate-800":i===3?"font-semibold text-violet-900":"text-slate-600"}`} key={cell}>{cell}</td>)}</tr>)}</tbody></table></div></div>
    <div className="grid gap-3 md:grid-cols-2"><div className="card p-5"><div className="text-xs font-bold uppercase tracking-widest text-emerald-700">The signal base</div><p className="mt-3 text-sm leading-6 text-slate-700"><Fact id="aa.scale" /></p><p className="mt-3 text-sm leading-6 text-slate-700"><Fact id="aa.consent" /></p></div><div className="rounded-lg border border-amber-200 bg-amber-50 p-5"><div className="text-xs font-bold uppercase tracking-widest text-amber-800">The honest constraint</div><p className="mt-3 text-sm leading-6 text-amber-950"><Fact id="uli.adoption" /></p></div></div>
    <div className="rounded-lg border border-violet-200 bg-violet-50 p-5 text-lg font-semibold leading-8 text-violet-950">Every new ULI data service is a new signal for the layer above. Complementary to RBIH by construction — and the weak-land-records constraint is precisely a reconciliation problem, which is what this layer does.</div>
  </div></Shell>; }
